site_name: Knowledge is Power
nav:
    - index.md
    - 'Linux Distribution Tutorial':
        - yocto/index.md
        - yocto/about-yocto.md
        - yocto/prerequisites.md
        - yocto/setup.md
        - yocto/initial-config.md
        - yocto/building-images.md
        - yocto/flashing-images.md
        - yocto/running-yocto.md
        - yocto/next-steps.md
theme:
    name: material
    palette:
        scheme: default
        primary: deep orange
    font:
        text: Roboto Slab
        code: Ubuntu Mono
    language: en
    features:
        - navigation.sections
        - toc.integrate
extra_css:
    - stylesheets/extra.css
markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.keys
    - pymdownx.tabbed:
        alternate_style: true
plugins:
    - search